# 修改数组的形状

In [ ]:
import numpy as np

|函数|描述
|--|--
|`reshape`|不改变数据的条件下修改形状
|`resize`|改变数组形状和大小
|`flat`|数组元素迭代器
|`flatten`|	返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
|`ravel`|返回展开数组

## numpy.reshape

In [ ]:
a = np.arange(6)
a

将形状修改为2乘3：

In [ ]:
a.shape = 2,3
a

与之对应的方法是 `reshape` ，但它**不会修改原来数组的值，而是返回一个新的数组**

In [ ]:
a.reshape(3,2)

In [ ]:
a

如果在 `reshape` 操作中将 `size `指定为-1，则会自动计算其他的 `size `大小

In [ ]:
a.reshape(3,-1)

## numpy.resize

numpy.resize 函数返回指定大小的**新数组**

如果新数组大小大于原始大小，则包含原始数组中的元素的**副本**

`numpy.resize(arr, shape)`

参数说明：


* `arr`：要修改大小的数组

* `shape`：返回数组的新形状

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
 
print '第一个数组：'
print a
print '\n'
 
print '第一个数组的形状：'
print a.shape
print '\n'
b = np.resize(a, (3,2))
 
print '第二个数组：'
print b
print ('\n')
 
print '第二个数组的形状：'
print b.shape
print '\n'
 
print '修改第二个数组的大小：'
b = np.resize(a,(3,3))
# 要注意 a 的第一行在 b 中重复出现，因为尺寸变大了
print b

## numpy.ndarray.resize

`numpy.ndarray.resize`与`numpy.resize ndarray`的区别

* `numpy.ndarray.resize`对数组进行原地(`in-place`)修改无返回值，而`numpy.resize`返回一个新的数组


* 当新的size比原来的size大时，`numpy.ndarray.resize`默认填充0,而`numpy.resize`将copy原数组中的值对新数组进行填充

`resize(new_shape, refcheck=True)`

参数说明：


* `new_shape`: tuple of ints, or n ints. Shape of resized array.


* `refcheckbool`: 默认为True，如果为False，引用计数将不会被check

新的size比原来的size小时，数组将会缩小(**Shrink**),缩小的顺序将按照其在内在中的存储顺序进行

In [ ]:
a = np.array([[0, 1], [2, 3]], order='C') ## 
print a
a.resize((2, 1))
print a

新的size比原来的size大时，`numpy.ndarray.resize`默认填充0

In [ ]:
a = np.array([[0, 1], [2, 3]], order='C') ## 
a.resize((3,3))
print a

默认情况下`refcheckbool=True`，则不能通过引用对象进行resize

In [ ]:
a = np.array([[0, 1], [2, 3]], order='C') ## 
c = a
c.resize((3,3))
print c

如果想通过引用对象进行resize,`refcheckbool`必须设置为False

In [ ]:
a = np.array([[0, 1], [2, 3]], order='C') ## 
c = a
c.resize((3,3), refcheck=False)
print c

使用view()对象也是不被允许的

In [ ]:
a = np.array([[0, 1], [2, 3]], order='C') ## 
c = a.view()
print c.base is a
c.resize((3,3), refcheck=False)
print c

## numpy.ndarray.flat

`numpy.ndarray.flat `是一个数组元素迭代器，通过迭代器可以对原数组的内容进行修改

In [ ]:
a = np.arange(9).reshape(3,3) 
print '原始数组：'
for row in a:
    print row
 
#对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print '迭代后的数组：'
for element in a.flat:
    print element

但此时修改 `b` 的值会影响 `a` ：

In [ ]:
b = a.flat
b[0] = 100
print a

## numpy.ndarray.flatten

`numpy.ndarray.flatten` 返回一份数组**拷贝**，对拷贝所做的修改不会影响原始数组,格式如下

`ndarray.flatten(order='C')`

参数说明：`order`：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序

In [ ]:
a = np.arange(8).reshape(2,4)
 
print '原数组：'
print a
print '\n'
# 默认按行
 
print '展开的数组：'
print a.flatten()
print '\n'
 
print '以 F 风格顺序展开的数组：'
print a.flatten(order = 'F')

## numpy.ravel

`numpy.ravel()` 展平的数组元素，顺序通常是"C风格"，返回的是数组**视图**，修改会影响原始数组。该函数接收两个参数：

`numpy.ravel(a, order='C')`

参数说明：`order`：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序

In [ ]:
a = np.arange(8).reshape(2,4)
 
print '原数组：'
print a
print '\n'

print '调用 ravel 函数之后：'
print a.ravel()
print '\n'
 
print '以 F 风格顺序调用 ravel 函数之后：'
print a.ravel(order = 'F')

# 翻转数组

|函数|描述
|--|--
|`transpose`|数组转置
|`ndarray.T`|和 self.transpose() 相同
|`rollaxis`|向后滚动指定的轴
|`swapaxes`|对换数组的两个轴

## `transpose()`

使用 `transpose` 返回原数组的另一种view，所以改变转置**会改变原来数组的值**

In [ ]:
a = np.arange(12)
a.shape = 3,4
print a
b = a.transpose() 
# 或者使用a的缩写属性
# b = a.T
print b
print b.base is a   # 如果内存来自其他对象，则为基础对象
b[0,1] = 100
print a

## numpy.rollaxis
`numpy.rollaxis`函数向后滚动特定的轴到一个特定位置，格式如下

`numpy.rollaxis(arr, axis, start)`

参数说明：

* `arr`：数组


* `axis`：要向后滚动的轴，其它轴的相对位置不会改变


* `start`：默认为零，表示完整的滚动。会滚动到特定位置

In [ ]:
a = np.arange(8).reshape(2,2,2)
 
print '原数组：'
print a
print '获取数组中一个值：'
print np.where(a==6)   
print a[1,1,0]  # 为 6
print '\n'
 
 
# 将轴 2 滚动到轴 0（宽度到深度）
 
print '调用 rollaxis 函数：'
b = np.rollaxis(a,2,0)
print b
# 查看元素 a[1,1,0]，即 6 的坐标，变成 [0, 1, 1]
# 最后一个 0 移动到最前面
print np.where(b==6) 
print '\n'

## numpy.swapaxes
`numpy.swapaxes`函数用于交换数组的两个轴，格式如下：

`numpy.swapaxes(arr, axis1, axis2)`

参数说明：

`arr`：输入的数组


`axis1`：对应第一个轴的整数


`axis2`：对应第二个轴的整数

In [ ]:
# 创建了三维的 ndarray
a = np.arange(8).reshape(2,2,2)
 
print '原数组：'
print a
print '\n'
# 现在交换轴 0（深度方向）到轴 2（宽度方向）
 
print '调用 swapaxes 函数后的数组：'
print np.swapaxes(a, 2, 0)

# 修改数组维度

## 使用 newaxis 增加数组维数

In [ ]:
a = np.arange(3)
np.shape(a)

In [ ]:
y = a[np.newaxis, :]
print y.shape
print y

根据插入位置的不同，可以返回不同形状的数组：

In [ ]:
y = a[:, np.newaxis]
y.shape

插入多个新维度：

In [ ]:
y = a[np.newaxis, np.newaxis, :]
y.shape

# squeeze 方法去除多余的轴

In [ ]:
a = np.arange(6)
a.shape = (2,1,3)

In [ ]:
b = a.squeeze()
b.shape

# 数组连接

|函数|描述
|--|--
|`concatenate`|连接沿现有轴的数组序列
|`stack`|沿着新的轴加入一系列数组
|`hstack`|水平堆叠序列中的数组（列方向）
|`vstack`|竖直堆叠序列中的数组（行方向）

### numpy.concatenate

`numpy.concatenate `函数用于沿指定轴连接相同形状的两个或多个数组，格式如下

`concatenate((a0,a1,...,aN), axis=0)`

参数说明：

* `a1, a2, ...`：相同类型的数组,这些数组要用 () 包括到一个元组中去
* `axis`：沿着它连接数组的轴，默认为 0,如果`axis`被设置为`None`，则数组在使用前会被拉平（不会影响原数组的值）

除了给定的轴外，这些数组其他轴的长度必须是一样的

In [ ]:
x = np.array([
        [0,1,2],
        [10,11,12]
    ])
y = np.array([
        [50,51,52],
        [60,61,62]
    ])
print x.shape
print y.shape

默认沿着第一维进行连接：

In [ ]:
z = np.concatenate((x,y))
z

In [ ]:
z.shape

如果`axis`被设置为`None`，则数组在使用前会被拉平（不会影响原数组的值）

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=None)

沿着第二维进行连接：

In [ ]:
z = np.concatenate((x,y), axis=1)
z

In [ ]:
z.shape

注意到这里 `x` 和 `y` 的形状是一样的，还可以将它们连接成三维的数组，但是 `concatenate` 不能提供这样的功能，不过可以这样：

In [ ]:
z = np.array((x,y))

In [ ]:
z.shape

## numpy.stack

`numpy.stack` 函数用于沿新轴连接数组序列，格式如下：

`numpy.stack(arrays, axis)`

参数说明：

* arrays：**相同形状**的数组序列


* axis：返回数组中的轴，输入数组沿着它来堆叠

## numpy.hstack

`numpy.hstack` 是` numpy.stack `函数的变体，它通过水平堆叠来生成数组

In [2]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print '第一个数组：'
print a
print '\n'
b = np.array([[5,6],[7,8]])
 
print '第二个数组：'
print b
print '\n'
 
print '水平堆叠：'
c = np.hstack((a,b))
print c
print '\n'

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


水平堆叠：
[[1 2 5 6]
 [3 4 7 8]]


