# numpy中的拷贝与视图

拷贝一般发生在：

* **Python序列**的切片操作，调用deepCopy()函数


* 调用 ndarray 的 copy() 函数产生一个副本

视图一般发生在：

* numpy 的切片操作返回原数据的视图


* 调用 ndarray 的 view() 函数产生一个视图

当计算和操作数组时，有时会将数据复制到新数组中，有时则不会。这通常是初学者混淆的根源。有三种情况
* 完全不复制


* 视图（浅拷贝）


* 深拷贝

## 完全不复制

In [1]:
import numpy as np

In [2]:
a = np.arange(12)
b = a                  # no new object is created
print b is a           # a and b are two names for the same ndarray object

b.shape = 3,4          # changes the shape of b
print a.shape

True
(3, 4)


Python将可变对象作为引用传递，因此函数调用不会复制

In [3]:
def f(x):
    print(id(x))

print id(a)                           # id is a unique identifier of an object
f(a)

139692460305664
139692460305664


## 视图或浅拷贝

不同的数组对象可以共享相同的数据。该`view`方法创建一个查看相同数据的新数组对象

In [4]:
c = a.view()
print c is a
print c.base is a                        # c is a view of the data owned by a
print c.flags.owndata
c.shape = 2,6                      # a's shape doesn't change
a.shape
c[0,4] = 1234                      # a's data changes
print a

False
True
False
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


切片数组会返回一个视图：

In [5]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
print a

[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


## 深拷贝

使用`copy()`方法生成数组及其数据的完整副本

In [6]:
d = a.copy()                        # a new array object with new data is created
print d is a
print d.base is a                   # d doesn't share anything with a
d[0,0] = 9999
print  a

False
False
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


有时，如果不再需要原始数组，则应在切片后调用 copy。例如，假设a是一个巨大的中间结果，最终结果b只包含a的一小部分，那么在用切片构造b时应该做一个深拷贝：

In [7]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a  # the memory of ``a`` can be released.

如果改为使用 b = a[:100]，则 a 由 b 引用，并且即使执行 del a 也会在内存中持久存在

In [8]:
a = np.arange(int(1e8))
b = a[:100]
del a  # the memory of ``a`` can be released.
print b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
